### ISSUE TITLE
Unable to set animations on headers

### ISSUE THREAD

**Issue by benjosantony** [TonicArtos/StickyGridHeaders#100]
I am unable to set animation on the headers of my gridView.

Below is the code
    gridView.setOnHeaderClickListener(new OnHeaderClickListener() {

```
        @Override
        public void onHeaderClick(AdapterView<?> arg0, View arg1, long arg2) {
            Log.d(TAG, "Header clicked ");
            Animation anim = AnimationUtils.loadAnimation(
                    AddCardsGridActivity.this, R.anim.slide_in_left);
            arg1.startAnimation(anim);

        }
    });
```

However there is no problem when I try to animate the grid item itself. 
How can I make the animation work for the headers ? or is it not possible ? 
Please advise.

**Comment by TonicArtos** [comment]
This project is no longer supported and has been replaced by [SuperSLiM](https://github.com/TonicArtos/SuperSLiM). While SuperSLiM is still in heavy development, I already consider it much better and more stable than StickyGridHeaders. SuperSLiM also sees regular versioned releases.
