### ISSUE TITLE
Use StickyGridHeadersGridView in Scrollview 

### ISSUE THREAD

**Issue by Tipsyume** [TonicArtos/StickyGridHeaders#120]
why StickyGridHeadersGridView display incomplete

**Comment by YLBFDEV** [comment]
GridView已经可以滚动不需要在外面嵌套 Scrollview。可以把Scrollview去掉试试看

**Comment by Tipsyume** [comment]
具体是这样的，一个页面除了gridview还有一些头部布局的，目前这个gridview不能addheader,嵌套在Scrollview里了！

**Comment by bejibx** [comment]
StickyGridHeadersGridView is scrollable by itself. You should never put one scrollable view inso another.

**Comment by wangshaolei** [comment]
@Tipsyume hi, how do you solve the problem? can y help me?

**Comment by wangshaolei** [comment]
I try the code : overriide onMeasure(){super.onMeasure(widthMeasureSpec, MeasureSpec.makeMeasureSpec(Integer.MAX_VALUE >> 2, MeasureSpec.AT_MOST));}
but find big empty view in the scrollview's bottom.
