### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by pablojacobi** [TonicArtos/StickyGridHeaders#40]
Hi!

I have been using StickyGridHeaders for a month, and it works great, but randomly when I load the gridview I get an exception like this.

0       java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to com.tonicartos.widget.stickygridheaders.StickyGridHeadersBaseAdapterWrapper$FillerView
1   at  com.tonicartos.widget.stickygridheaders.StickyGridHeadersBaseAdapterWrapper.getFillerView(StickyGridHeadersBaseAdapterWrapper.java:261)
2   at  com.tonicartos.widget.stickygridheaders.StickyGridHeadersBaseAdapterWrapper.getView(StickyGridHeadersBaseAdapterWrapper.java:177)
3   at  android.widget.AbsListView.obtainView(AbsListView.java:2597)
4   at  android.widget.GridView.makeAndAddView(GridView.java:1344)
5   at  android.widget.GridView.makeRow(GridView.java:344)
6   at  android.widget.GridView.fillSpecific(GridView.java:546)
7   at  android.widget.GridView.layoutChildren(GridView.java:1243)
8   at  android.widget.AbsListView.onLayout(AbsListView.java:2431)
9   at  android.view.View.layout(View.java:14482)
10  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
11  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
12  at  android.view.View.layout(View.java:14482)
13  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
14  at  android.widget.LinearLayout.setChildFrame(LinearLayout.java:1669)
15  at  android.widget.LinearLayout.layoutVertical(LinearLayout.java:1527)
16  at  android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
17  at  android.view.View.layout(View.java:14482)
18  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
19  at  android.widget.RelativeLayout.onLayout(RelativeLayout.java:1021)
20  at  android.view.View.layout(View.java:14482)
21  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
22  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
23  at  android.view.View.layout(View.java:14482)
24  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
25  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
26  at  android.view.View.layout(View.java:14482)
27  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
28  at  android.widget.RelativeLayout.onLayout(RelativeLayout.java:1021)
29  at  android.view.View.layout(View.java:14482)
30  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
31  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
32  at  android.view.View.layout(View.java:14482)
33  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
34  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
35  at  android.view.View.layout(View.java:14482)
36  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
37  at  android.widget.LinearLayout.setChildFrame(LinearLayout.java:1669)
38  at  android.widget.LinearLayout.layoutVertical(LinearLayout.java:1527)
39  at  android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
40  at  android.view.View.layout(View.java:14482)
41  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
42  at  android.widget.RelativeLayout.onLayout(RelativeLayout.java:1021)
43  at  android.view.View.layout(View.java:14482)
44  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
45  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
46  at  android.view.View.layout(View.java:14482)
47  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
48  at  android.widget.LinearLayout.setChildFrame(LinearLayout.java:1669)
49  at  android.widget.LinearLayout.layoutVertical(LinearLayout.java:1527)
50  at  android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
51  at  android.view.View.layout(View.java:14482)
52  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
53  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
54  at  android.view.View.layout(View.java:14482)
55  at  android.view.ViewGroup.layout(ViewGroup.java:4469)
56  at  android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2147)
57  at  android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1966)
58  at  android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1179)
59  at  android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4861)
60  at  android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
61  at  android.view.Choreographer.doCallbacks(Choreographer.java:562)
62  at  android.view.Choreographer.doFrame(Choreographer.java:532)
63  at  android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
64  at  android.os.Handler.handleCallback(Handler.java:725)
65  at  android.os.Handler.dispatchMessage(Handler.java:92)
66  at  android.os.Looper.loop(Looper.java:137)
67  at  android.app.ActivityThread.main(ActivityThread.java:5293)
68  at  java.lang.reflect.Method.invokeNative(Native Method)
69  at  java.lang.reflect.Method.invoke(Method.java:511)
70  at  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
71  at  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
72  at  dalvik.system.NativeStart.main(Native Method)

May I'm doing something wrong, but is weird I cannot replicate this error easily, just happens.

Thanks in advance for any help!

**Comment by anbarasu-seven** [comment]
Hi, am having 2 tabs at the top of the activity,below that a stickyHeaderGridView that will update its content depends on the tab selected at the top, here the problem is when clicking 2'nd tab i need stickyHeaderGridView funtionality that works fine, but when clicking the 1'st tab i want to use the normal gridview functionality instead stickyHeaderGridView, am stucking more than 2 days ,kindly give me any suggestion.

**Comment by marcohc** [comment]
Using Adapter.notifyDataSetChanged() instead of creating it again works fine and fix the bug. Thank you all.

**Comment by anbarasu-seven** [comment]
sorry for late reply. i fixed it using the same way you mentioned above,
after some documentation about updating data in list and in grids

..thanks for reply

**Comment by marcohc** [comment]
Eh...ok it does not work, even using the notifyDataSetChanged() it throws from time to time the same exception, any other walk around or fix?

**Comment by anbarasu-seven** [comment]
can you say me clearly, in which class and line you face the problem
exactly......

**Comment by marcohc** [comment]
Inside _StickyGridHeadersBaseAdapterWrapper_

```
private FillerView getFillerView(View convertView, ViewGroup parent, View lastViewSeen) {
    FillerView fillerView = (FillerView) convertView;
    if (fillerView == null) {
        fillerView = new FillerView(mContext);
    }

    fillerView.setMeasureTarget(lastViewSeen);

    return fillerView;
}
```

This cast _FillerView fillerView = (FillerView) convertView;_ throws the ClassCastException.

**Comment by anbarasu-seven** [comment]
hello marco,

your calling this getFillerView(View convertView, ViewGroup parent, View
lastViewSeen) from 2 places.ie (from)inside the getView method of the same
adapter class

like below

 @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        Position adapterPosition = translatePosition(position);
        if (adapterPosition.mPosition == POSITION_HEADER) {
            HeaderFillerView v =
getHeaderFillerView(adapterPosition.mHeader, convertView, parent);
            View view = mDelegate.getHeaderView(adapterPosition.mHeader,
(View)v.getTag(), parent);
            mGridView.detachHeader((View) v.getTag());
            v.setTag(view);
            mGridView.attachHeader(view);
            convertView = v;
            mLastHeaderViewSeen = v;
            v.forceLayout();
        } else if (adapterPosition.mPosition == POSITION_HEADER_FILLER) {
            convertView = getFillerView(convertView, parent,
mLastHeaderViewSeen);
            convertView.forceLayout();
        } else if (adapterPosition.mPosition == POSITION_FILLER) {
            convertView = getFillerView(convertView, parent, mLastViewSeen);
        } else {
            convertView = mDelegate.getView(adapterPosition.mPosition,
convertView, parent);
            mLastViewSeen = convertView;
        }

```
    return convertView;
}
```

in the above get view method note the FIRST if condition,

ie.   if (adapterPosition.mPosition == POSITION_HEADER) {
            HeaderFillerView v =
getHeaderFillerView(adapterPosition.mHeader, convertView, parent);
            View view = mDelegate.getHeaderView(adapterPosition.mHeader,
(View)v.getTag(), parent);
            mGridView.detachHeader((View) v.getTag());
            v.setTag(view);
            mGridView.attachHeader(view);
            convertView = v;
            mLastHeaderViewSeen = v;
            v.forceLayout();
        }

in the above code: note the 2nd line

HeaderFillerView v = getHeaderFillerView(adapterPosition.mHeader,
convertView, parent);

above line of code creates view that a type of HeaderFillerView (NOTE - NOT
A TYPE OF FillerView).

 in the 6th line you are backing up that view to convertview  as
 convertView = v;

now your convertView is ready with type of HeaderFillerView.

YOUR PROBLEM ARISES HERE:
ie in both the "else if" condition of the same getView method

 else if (adapterPosition.mPosition == POSITION_HEADER_FILLER) {
            convertView = getFillerView(convertView, parent,
mLastHeaderViewSeen);
            convertView.forceLayout();
        } else if (adapterPosition.mPosition == POSITION_FILLER) {
            convertView = getFillerView(convertView, parent, mLastViewSeen);
        }

note 2nd line(or 5th line) of the above code

already your convertView is ready with the type of HeaderFillerView(ie.
convertView = v;), your passing that converView to another method like below
getFillerView(convertView, parent, mLastHeaderViewSeen);

right,,,

but in the getFillerView method definition your trying to convert(cast)
that view to FillerView, actualy that is not a type of FillerView,actually
a type of HeaderFillerView

that is why it shows classcasting exception;

ie your Casting a view that is type of HeaderFillerView to FillerView......

**Comment by gentledepp** [comment]
@anbarasu-seven : Can you provide a fix? :-/

**Comment by TonicArtos** [comment]
Have you considered using the StickGridHeaders replacement? I know it isn't exactly the same and I am still working on it. However, I think it is much better. 

If you don't want to use it, please tell me why. Thanks.

**Comment by anbarasu-seven** [comment]
Step 1:
private HeaderFillerView getHeaderFillerView(int headerPosition, View
convertView,
            ViewGroup parent) {
        HeaderFillerView headerFillerView = (HeaderFillerView)convertView;
        if (headerFillerView == null) {
            headerFillerView = new HeaderFillerView(mContext);
        }

```
    return headerFillerView;
}
```

replace above method by

private HeaderFillerView getHeaderFillerView(int headerPosition, View
convertView,
            ViewGroup parent) {
if(convertView instanceOf HeaderFillerView ){
 HeaderFillerView headerFillerView = (HeaderFillerView)convertView;
}else{
// convertView==null also come here
  headerFillerView = new HeaderFillerView(mContext);
}
}

Step 2:

 private FillerView getFillerView(View convertView, ViewGroup parent, View
lastViewSeen) {
        FillerView fillerView = (FillerView)convertView;
        if (fillerView == null) {
            fillerView = new FillerView(mContext);
        }

```
    fillerView.setMeasureTarget(lastViewSeen);

    return fillerView;
}
```

replace above method by

private FillerView getFillerView(View convertView, ViewGroup parent, View
lastViewSeen) {
if(convertView instanceOf FillerView){
 FillerView fillerView = (FillerView)convertView;
}else{
//convertView==null also come here
 fillerView = new FillerView(mContext);
}
       fillerView.setMeasureTarget(lastViewSeen);
        return fillerView;
    }

**Comment by gentledepp** [comment]
@anbarasu-seven Hey thanks - I'll see if that fixes the bug :)
Bzw - why don't you want to send a pull-request? Seems you already fixed it, right?
I have no problem re-compiling the library on my own, but you might do a loooots of folks out there a big favor ;-)

@TonicArtos I don't know anything about a "StickyGridHeaders repalcement" - please tell me more! What is it, where can I find it?

**Comment by TonicArtos** [comment]
It is mentioned in the readme. It is a RecyclerView LayoutManager called SuperSLiM. You can find it [here](http://github.com/TonicArtos/SuperSLiM).

**Comment by marcohc** [comment]
I can't reproduce the CastException again, thanks a lot @anbarasu-seven!

**Comment by anbarasu-seven** [comment]
thanks , happy coding.......enjoy exceptions.......
