### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by pablojacobi** [TonicArtos/StickyGridHeaders#70]
Hi,

I just received this crash from Sticky Grid

java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to co.seahorse.android.views.photogallery.adapter.ItemAdapter$ViewHolder
1   at  co.seahorse.android.views.photogallery.adapter.ItemAdapter.getView(ItemAdapter.java:95)
2   at  com.tonicartos.widget.stickygridheaders.StickyGridHeadersBaseAdapterWrapper.getView(StickyGridHeadersBaseAdapterWrapper.java:190)
3   at  android.widget.AbsListView.obtainView(AbsListView.java:2445)
4   at  android.widget.GridView.makeAndAddView(GridView.java:1331)
5   at  android.widget.GridView.makeRow(GridView.java:331)
6   at  android.widget.GridView.fillDown(GridView.java:283)
7   at  android.widget.GridView.fillSpecific(GridView.java:552)
8   at  android.widget.GridView.layoutChildren(GridView.java:1230)
9   at  android.widget.AbsListView.onLayout(AbsListView.java:2296)
10  at  android.view.View.layout(View.java:14055)
11  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
12  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
13  at  android.view.View.layout(View.java:14055)
14  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
15  at  android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
16  at  android.view.View.layout(View.java:14055)
17  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
18  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
19  at  android.view.View.layout(View.java:14055)
20  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
21  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
22  at  android.view.View.layout(View.java:14055)
23  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
24  at  android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
25  at  android.view.View.layout(View.java:14055)
26  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
27  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
28  at  android.view.View.layout(View.java:14055)
29  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
30  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
31  at  android.view.View.layout(View.java:14055)
32  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
33  at  android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
34  at  android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
35  at  android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
36  at  android.view.View.layout(View.java:14055)
37  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
38  at  android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
39  at  android.view.View.layout(View.java:14055)
40  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
41  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
42  at  android.view.View.layout(View.java:14055)
43  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
44  at  android.widget.LinearLayout.setChildFrame(LinearLayout.java:1655)
45  at  android.widget.LinearLayout.layoutVertical(LinearLayout.java:1513)
46  at  android.widget.LinearLayout.onLayout(LinearLayout.java:1426)
47  at  android.view.View.layout(View.java:14055)
48  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
49  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
50  at  android.view.View.layout(View.java:14055)
51  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
52  at  android.widget.FrameLayout.onLayout(FrameLayout.java:448)
53  at  android.view.View.layout(View.java:14055)
54  at  android.view.ViewGroup.layout(ViewGroup.java:4604)
55  at  android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1992)
56  at  android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1813)
57  at  android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1112)
58  at  android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4472)
59  at  android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
60  at  android.view.Choreographer.doCallbacks(Choreographer.java:555)
61  at  android.view.Choreographer.doFrame(Choreographer.java:525)
62  at  android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
63  at  android.os.Handler.handleCallback(Handler.java:615)
64  at  android.os.Handler.dispatchMessage(Handler.java:92)
65  at  android.os.Looper.loop(Looper.java:137)
66  at  android.app.ActivityThread.main(ActivityThread.java:4898)
67  at  java.lang.reflect.Method.invokeNative(Native Method)
68  at  java.lang.reflect.Method.invoke(Method.java:511)
69  at  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
70  at  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
71  at  dalvik.system.NativeStart.main(Native Method)

My problem is this only has happened one time (with a couple of active users), so I'm not sure about why this happened.

My holder is something like

private class ViewHolder {
        public ImageView commentIndicator;
        public ImageView image;
        public ImageView videoIndicator;
        public FrameLayout frame_image;
        public ProgressBar progressBar;
    }

Thanks in advance for any help

Regards!

**Comment by tenaz92** [comment]
I have got the same issue.Is any fix available?
