### ISSUE TITLE
AdapterView.getItemAtPosition()

### ISSUE THREAD

**Issue by NicolasSiver** [TonicArtos/StickyGridHeaders#81]
Works incorrectly. 
In most cases it returns null, because code assumes it's a header.
Check 328 line code in StickyGridHeadersBaseAdapterWrapper.
Code will return Header type for zero position.

**Comment by jam01** [comment]
The fix you suggest is to modify the getItem in StickyGridHeadersBaseAdapterWrapper, right? Or can you override it from somewhere else?
