### ISSUE TITLE
Crash on getView

### ISSUE THREAD

**Issue by sahilmiglani** [TonicArtos/StickyGridHeaders#89]
Stack track--

Stack trace -

02-05 13:31:58.114: E/AndroidRuntime(1724): at com.tonicartos.widget.stickygridheaders.StickyGridHeadersBaseAdapterWrapper.getView(StickyGridHeadersBaseAdapterWrapper.java:193)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.AbsListView.obtainView(AbsListView.java:2263)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.GridView.makeAndAddView(GridView.java:1345)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.GridView.makeRow(GridView.java:345)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.GridView.fillDown(GridView.java:287)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.GridView.fillFromTop(GridView.java:421)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.GridView.layoutChildren(GridView.java:1233)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.AbsListView.onLayout(AbsListView.java:2091)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.View.layout(View.java:14817)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewGroup.layout(ViewGroup.java:4631)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.View.layout(View.java:14817)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewGroup.layout(ViewGroup.java:4631)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1660)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.LinearLayout.onLayout(LinearLayout.java:1436)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.View.layout(View.java:14817)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewGroup.layout(ViewGroup.java:4631)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.ScrollView.onLayout(ScrollView.java:1468)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.View.layout(View.java:14817)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewGroup.layout(ViewGroup.java:4631)
02-05 13:31:58.114: E/AndroidRuntime(1724): at couk.jenxsol.parallaxscrollview.views.ParallaxScrollView.onLayout(ParallaxScrollView.java:277)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.View.layout(View.java:14817)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewGroup.layout(ViewGroup.java:4631)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.View.layout(View.java:14817)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewGroup.layout(ViewGroup.java:4631)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1589)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.View.layout(View.java:14817)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewGroup.layout(ViewGroup.java:4631)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.View.layout(View.java:14817)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewGroup.layout(ViewGroup.java:4631)
02-05 13:31:58.114: E/AndroidRuntime(1724): at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.View.layout(View.java:14817)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewGroup.layout(ViewGroup.java:4631)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.View.layout(View.java:14817)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewGroup.layout(ViewGroup.java:4631)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1744)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.Choreographer.doCallbacks(Choreographer.java:574)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.Choreographer.doFrame(Choreographer.java:544)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.os.Handler.handleCallback(Handler.java:733)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.os.Handler.dispatchMessage(Handler.java:95)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.os.Looper.loop(Looper.java:136)
02-05 13:31:58.114: E/AndroidRuntime(1724): at android.app.ActivityThread.main(ActivityThread.java:5017)
02-05 13:31:58.114: E/AndroidRuntime(1724): at java.lang.reflect.Method.invokeNative(Native Method)
02-05 13:31:58.114: E/AndroidRuntime(1724): at java.lang.reflect.Method.invoke(Method.java:515)
02-05 13:31:58.114: E/AndroidRuntime(1724): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
02-05 13:31:58.114: E/AndroidRuntime(1724): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)

**Comment by hendrawd** [comment]
This problem still occurred until now. I don't switch to SuperSLiM yet, because last time i use it, it can't detect end of scroll :(. Is there any workaround to solve this problem?
